"""
=========================================
Static variables and mappings we used in our FL QC process.
=========================================
Authors: Veronika Potter, Hoan Tran, and Umberto Mezzucchelli
Email: potter[dot]v[at]northeastern.edu (potter.v@northeastern.edu)
"""

LABEL_SETS = ["HIGH LEVEL BEHAVIOR", "PA TYPE", "POSTURE"]

PA_TO_HLB = {
    "Sweeping": "Cleaning",
    "Vacuuming": "Cleaning",
    "Dusting": "Cleaning",
    "Wet_Mopping": "Cleaning",
    "Dry_mopping": "Cleaning",
    "Cycling_Active_Pedaling_Regular_Bicycle": "Cycling_Regular_Bicycle",
    "Scrubbing_Dishes": "Doing_Dishes",
    "Rinsing_Dishes": "Doing_Dishes",
    "Drying_Dishes": "Doing_Dishes",
    "Loading/Unloading_Dishwasher": "Doing_Dishes",
    "Ironing": "Doing_Laundry",
    "Folding_Clothes": "Doing_Laundry",
    "Putting_Clothes_Away": "Doing_Laundry",
    "Loading/Unloading_Washing_Machine/Dryer": "Doing_Laundry",
    "Doing_Resistance_Training_Free_Weights": "Doing_Resistance_Training",
    "Doing_Resistance_Training_Other": "Doing_Resistance_Training",
    "Cycling_Active_Pedaling_Stationary_Bike": "Exercising_Gym_Stationary_Bicycle",
    "Brushing_Teeth": "Grooming/Self_Care",
    "Flossing_Teeth": "Grooming/Self_Care",
    "Brushing/Combing_Hair": "Grooming/Self_Care",
    "Blowdrying_Hair": "Grooming/Self_Care",
    "Washing_Face": "Grooming/Self_Care",
    "Applying_Makeup": "Grooming/Self_Care",
    "Chopping_Food": "Cooking/Prepping_Food",
    "Stirring_Food": "Cooking/Prepping_Food",
    "Watering_Plants": "Gardening",
}

PA_TO_POS = {
    "Walking_Up_Stairs": ["In_Position_Upright"],
    "Walking": ["In_Position_Upright"],
    "Standing_Still": ["In_Position_Upright"],
    "Lying_Still": [
        "Lying_On_Back",
        "Lying_On_Right_Side",
        "Lying_On_Stomach",
        "Lying_On_Left_Side",
    ],
    "Standing_With_Movement": ["In_Position_Upright"],
    "Walking_Treadmill": ["In_Position_Upright"],
    "Running_Treadmill": ["In_Position_Upright"],
    "Sitting_Still": ["In_Position_Sitting", "In_Position_Reclining/Slouching"],
    "Sitting_With_Movement": ["In_Position_Sitting", "In_Position_Reclining/Slouching"],
    "Folding_Clothes": [
        "In_Position_Upright",
        "In_Postion_Sitting",
        "In_Position_Reclining/Slouching",
    ],
    "Sit Recline Talk Lab": ["In_Position_Sitting", "In_Position_Reclining/Slouching"],
    "Cycling_Active_Pedaling_Regular_Bicycle": ["In_Position_Sitting"],
    "Sweeping": ["In_Position_Upright"],
    "Vacuuming": ["In_Position_Upright"],
    "Walking_Down_Stairs": ["In_Position_Upright"],
    "Kneeling_With_Movement": ["In_Position_Kneeling"],
    "Playing_Frisbee": ["In_Position_Upright"],
    "Lying_With_Movement": [
        "Lying_On_Back",
        "Lying_On_Right_Side",
        "Lying_On_Stomach",
        "Lying_On_Left_Side",
    ],
    "Kneeling_Still": ["In_Position_Kneeling"],
    "Walking_Slow": ["In_Position_Upright"],
    "Walking_Fast": ["In_Position_Upright"],
    "Cycling_Active_Pedaling_Stationary_Bike": ["In_Position_Sitting"],
    "Organizing_Shelf/Cabinet": [
        "In_Position_Kneeling",
        "In_Position_Upright",
        "Posture_Other",
        "Posture_Too_Complex",
    ],
    "Applying_Makeup": ["In_Position_Upright"],
    "Blowdrying_Hair": ["In_Position_Upright"],
    "Brushing_Teeth": ["In_Position_Upright"],
    "Brushing/Combing/Tying_Hair": ["In_Position_Upright"],
    "Dry_Mopping": ["In_Position_Upright"],
    "Dusting": ["In_Position_Upright"],
    "Flossing_Teeth": ["In_Position_Upright"],
    "Ironing": ["In_Position_Upright"],
    "Loading/Unloading_Washing_Machine/Dryer": ["In_Position_Upright"],
    "Puttering_Around": ["In_Position_Upright"],
    "Putting_Clothes_Away": ["In_Position_Upright"],
    "Showering": ["In_Position_Upright"],
    "Shoveling_Mud_Snow": ["In_Position_Upright"],
    "Washing_Face": ["In_Position_Upright"],
    "Washing_Hands": ["In_Position_Upright"],
    "Watering_Plants": ["In_Position_Upright"],
    "Wet_Mopping": ["In_Position_Upright"],
}

FL_PA_LABELS = [
    "Applying_Makeup",
    "Bathing",
    "Blowdrying_Hair",
    "Brushing_Teeth",
    "Brushing/Combing/Tying_Hair",
    "Cycling_Active_Pedaling_Regular_Bicycle",
    "Cycling_Active_Pedaling_Stationary_Bike",
    "Doing_Resistance_Training_Free_Weights",
    "Doing_Resistance_Training_Other",
    "Dry_Mopping",
    "Dusting",
    "Flossing_Teeth",
    "Folding_Clothes",
    "Ironing",
    "Kneeling_Still",
    "Kneeling_With_Movement",
    "Loading/Unloading_Washing_Machine/Dryer",
    "Lying_Still",
    "Lying_With_Movement",
    "Organizing_Shelf/Cabinet",
    "PA_Type_Other",
    "PA_Type_Too_Complex",
    "PA_Type_Unlabeled",
    "PA_Type_Video_Unavailable/Indecipherable",
    "Playing_Frisbee",
    "Puttering_Around",
    "Putting_Clothes_Away",
    "Running_Non-Treadmill",
    "Running_Treadmill",
    "Showering",
    "Shoveling_Mud/Snow",
    "Sitting_Still",
    "Sitting_With_Movement",
    "Standing_Still",
    "Standing_With_Movement",
    "Sweeping",
    "Synchronizing_Sensors",
    "Vacuuming",
    "Walking_Down_Stairs",
    "Walking_Fast",
    "Walking_Slow",
    "Walking_Treadmill",
    "Walking_Up_Stairs",
    "Walking",
    "Washing_Face",
    "Washing_Hands",
    "Watering_Plants",
    "Wet_Mopping",
]
